### ISSUE TITLE
Log out Button doesn't Wipe Token

### ISSUE THREAD

**Issue by Jnv821** [Jnv821/4Geeks-Back-To-The-80s#75]
The Log-out button is currently not wiping the token after the user logs out. If an user were to authenticate correctly after someone has logged in they will log in as the previous account and not their actual one.

**This is a major security problem and needs a fix as soon as possible.** 

To replicate:

1. Log in as user "A"
2. Go to their profile, Check its correct
3. Log out
4. Log in as User "B"
5. Go to their profile. **Here it will be displaying user's A information and will be logged as user A**
6. Log out
7. Log in as user "A"
8. Go to their profile. **Here it will be displaying user's B information and will be logged as user B**

**Comment by sandrafepu** [comment]
José, he linkado un pull request que soluciona el problema.
